config:
  global:
    title: 这是一个是所有环境通用的配置参数,也就是主配置参数
    context: 在实际开发中，不同环境使用不同的配置，但有些配置是通用的，这个也是很好的
    note: java默认的配置文件是properties文件，但这里使用了yml配置文件,而不使用properties配置文件.从这里看就可以发现，yml配置的优势.其实除了这里的优势外，yml配置的优势还有许多，你可以在使用时慢慢体会